version: '3.4'

services:
  mongodbcontainer:
    container_name: mongodbcontainer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=aBX90#keq2Y3
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

  postgresdb:
    container_name: postgresdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=healthCENTER1997
      - POSTGRES_DB=AppointmentsDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=health.center@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=healthCENTER1997
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  employeeinformation.api:
    container_name: employeeinformation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
      - "GrpcSettings:ImpressionUrl=http://impressions.grpc"
    depends_on:
      - mongodbcontainer
      - impressions.grpc
    ports:
      - "8000:80"

  discounts.api:
    container_name: discounts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8001:80"

  impressions.api:
    container_name: impressions.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8002:80"

  reports.api:
    container_name: reports.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8003:80"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;TrustServerCertificate=True;Database=IdentityDb;User Id=sa;Password=aBX90#keq2Y3;"
    depends_on:
      - mssql
    ports:
      - "4000:80"

  impressions.grpc:
    container_name: impressions.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8004:80"

  appointments.api:
    container_name: appointments.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=postgresdb;Port=5432;Database=AppointmentsDb;User Id=admin;Password=healthCENTER1997;"
    depends_on:
      - postgresdb 
    ports:
      - "8005:80"

  discounts.grpc:
    container_name: discounts.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8006:80"

