version: '3.4'

services:
  mongodbcontainer:
    image: mongo

  employeeinformation.api:
    image: ${DOCKER_REGISTRY-}employeeinformationapi
    build:
      context: .
      dockerfile: Services/EmployeeInformation/EmployeeInformation.API/Dockerfile

  discounts.api:
    image: ${DOCKER_REGISTRY-}discountsapi
    build:
      context: .
      dockerfile: Services/Discounts/Discounts.API/Dockerfile

volumes:
  mongo_data: