version: '3.4'

services:
  mongodbcontainer:
    container_name: mongodbcontainer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  employeeinformation.api:
    container_name: employeeinformation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8000:80"

  discounts.api:
    container_name: discounts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8001:80"