version: '3.4'

services:
  employeedb:
    container_name: employeedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  employeeinformation.api:
    container_name: employeeinformation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://employeedb:27017"
    depends_on:
      - employeedb
    ports:
      - "8000:80"