version: '3.4'

services:
  mongodbcontainer:
    container_name: mongodbcontainer
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=aBX90#keq2Y3
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

  employeeinformation.api:
    container_name: employeeinformation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8000:80"

  discounts.api:
    container_name: discounts.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8001:80"

  impressions.api:
    container_name: impressions.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8002:80"

  reports.api:
    container_name: reports.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodbcontainer:27017"
    depends_on:
      - mongodbcontainer
    ports:
      - "8003:80"


  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;TrustServerCertificate=True;Database=IdentityDb;User Id=sa;Password=aBX90#keq2Y3;"
    depends_on:
      - mssql
    ports:
      - "4000:80"

