version: '3.4'

services:
  mongodbcontainer:
    image: mongo

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  postgresdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  employeeinformation.api:
    image: ${DOCKER_REGISTRY-}employeeinformationapi
    build:
      context: .
      dockerfile: Services/EmployeeInformation/EmployeeInformation.API/Dockerfile

  discounts.api:
    image: ${DOCKER_REGISTRY-}discountsapi
    build:
      context: .
      dockerfile: Services/Discounts/Discounts.API/Dockerfile

  impressions.api:
    image: ${DOCKER_REGISTRY-}impressionsapi
    build:
      context: .
      dockerfile: Services/Impressions/Impressions.API/Dockerfile

  reports.api:
    image: ${DOCKER_REGISTRY-}reportsapi
    build:
      context: .
      dockerfile: Services/Reports/Report.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  impressions.grpc:
    image: ${DOCKER_REGISTRY-}impressionsgrpc
    build:
      context: .
      dockerfile: Services/Impressions/Impressions.GRPC/Dockerfile

  appointments.api:
    image: ${DOCKER_REGISTRY-}appointmentsapi
    build:
      context: .
      dockerfile: Services/Appointments/Appointments.API/Dockerfile

  discounts.grpc:
    image: ${DOCKER_REGISTRY-}discountsgrpc
    build:
      context: .
      dockerfile: Services/Discounts/Discounts.GRPC/Dockerfile

volumes:
  mongo_data:
  mssql_data:
  postgres_data:
  pgadmin_data:

